experiment_name: baseline_v1_inference
checkpoint: checkpoints/baseline_v1/last.ckpt
output_dir: predictions/baseline_v1

data:
  path: /scratch3/NCEPDEV/da/Azadeh.Gholoubi/zarr
  start_date: 2025-01-01
  end_date: 2025-01-02
  batch_size: 1

resources:
  devices: 1
  num_nodes: 1

eval_mode: false