instrument_weights:
  atms: 1.0
  surface_pressure: 1.0
# radiosonde: 1.0

channel_weights:
  atms: [1, 1, 1, 1, 1, 1, 0.8, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.7, 0.7, 0.7, 1, 1, 1, 1, 1, 1]       # length 22
  surface_pressure: [1.0]
# radiosonde: [...]

