Region: us-east-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t3.micro
  Networking:
    SubnetId: subnet-063bbad948bc91ba5
  Ssh:
    KeyName: ron_key_2
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: gpu
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-063bbad948bc91ba5
      ComputeResources:
        - Name: compute
          InstanceType: <INSTANCE_TYPE>
          MinCount: 0
          MaxCount: 2
SharedStorage:
  - Name: fsx
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      DeploymentType: SCRATCH_2
      StorageCapacity: 1200
      ImportPath: s3://noaa-ocelot/<DATA_SOURCE>
      ExportPath: s3://noaa-ocelot/output
      AutoImportPolicy: NEW_CHANGED
      #AutoExportPolicy: ON_CLOSE

