Region: <REGION>

Image:
  Os: <OS>

Iam:
  Roles:
    LambdaFunctionsRole: <ADMIN_ROLE>

HeadNode:
  InstanceType: <HEAD_NODE_INSTANCE>
  Iam:
    InstanceRole: <HEAD_NODE_ROLE>
  Networking:
    SubnetId: <SUBNET_ID>
  Ssh:
    KeyName: ron_key_2

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: gpu
      CapacityType: SPOT
      Iam:
        InstanceRole: <COMPUTE_NODE_ROLE>
      Networking:
        SubnetIds:
          - <SUBNET_ID>
      ComputeResources:
        - Name: compute
          InstanceType: <INSTANCE_TYPE>
          MinCount: 0
          MaxCount: 2
      CustomActions:
        OnNodeStart:
          Script: <ON_NODE_START_SCRIPT>
        OnNodeConfigured:
          Script: <ON_NODE_CONFIGURED_SCRIPT>

SharedStorage:
  - Name: fsx
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      DeploymentType: SCRATCH_2
      StorageCapacity: 1200
      ImportPath: <IMPORT_PATH>
      ExportPath: <EXPORT_PATH>
      AutoImportPolicy: NEW_CHANGED


