data types:
  - name: atms
    type: tank
    num_tasks: 24
    batch_days: 15
    mapping: bufr_atms.py
    paths:
      - 00/atmos/gdas.t00z.atms.tm00.bufr_d
      - 06/atmos/gdas.t06z.atms.tm00.bufr_d
      - 12/atmos/gdas.t12z.atms.tm00.bufr_d
      - 18/atmos/gdas.t18z.atms.tm00.bufr_d

  - name: surface_obs
    type: tank
    num_tasks: 4
    batch_days: 30
    mapping: bufr_surface_obs.py
    paths:
      - 00/atmos/gdas.t00z.prepbufr
      - 06/atmos/gdas.t06z.prepbufr
      - 12/atmos/gdas.t12z.prepbufr
      - 18/atmos/gdas.t18z.prepbufr

  - name: radiosonde
    type: tank
    num_tasks: 4
    batch_days: 30
    mapping: bufr_radiosonde.py
    paths:
      - 00/atmos/gdas.t00z.prepbufr
      - 06/atmos/gdas.t06z.prepbufr
      - 12/atmos/gdas.t12z.prepbufr
      - 18/atmos/gdas.t18z.prepbufr

  - name: ascat
    type: tank
    num_tasks: 4
    batch_days: 30
    mapping: bufr_ascat.py
    paths:
      - 00/atmos/gdas.t00z.ascatt.tm00.bufr_d
      - 06/atmos/gdas.t06z.ascatt.tm00.bufr_d
      - 12/atmos/gdas.t12z.ascatt.tm00.bufr_d
      - 18/atmos/gdas.t18z.ascatt.tm00.bufr_d

  - name: seviri
    type: tank
    num_tasks: 4
    batch_days: 30
    mapping: bufr_seviri.py
    paths:
      - 00/atmos/gdas.t00z.sevcsr.tm00.bufr_d
      - 06/atmos/gdas.t06z.sevcsr.tm00.bufr_d
      - 12/atmos/gdas.t12z.sevcsr.tm00.bufr_d
      - 18/atmos/gdas.t18z.sevcsr.tm00.bufr_d

  - name: ssmis
    type: tank
    num_tasks: 4
    batch_days: 30
    mapping: bufr_ssmis.py
    paths:
      - 00/atmos/gdas.t00z.ssmisu.tm00.bufr_d
      - 06/atmos/gdas.t06z.ssmisu.tm00.bufr_d
      - 12/atmos/gdas.t12z.ssmisu.tm00.bufr_d
      - 18/atmos/gdas.t18z.ssmisu.tm00.bufr_d

  - name: amsua
    type: tank
    num_tasks: 4
    batch_days: 30
    mapping: bufr_amsua.py
    paths:
      - 00/atmos/gdas.t00z.1bamua.tm00.bufr_d
      - 06/atmos/gdas.t06z.1bamua.tm00.bufr_d
      - 12/atmos/gdas.t12z.1bamua.tm00.bufr_d
      - 18/atmos/gdas.t18z.1bamua.tm00.bufr_d

  - name: iasi_pca
    type: pca
    num_tasks: 4
    batch_days: 30
    mapping: pca_iasi.py
    directory: /scratch3/NCEPDEV/stmp/Andrew.Collard/IASI_PCA/bufr
    filename_regex: M03-IASI-IASPCS1C-NA-1.0-(?P<start_time>\d{14}).000000000Z-(?P<end_time>\d{14})-4887062-d+\.bfr

