hidden_dim: 192
latent_step_hours: 3

mesh:
  type: fixed  # fixed | hierarchical
  splits: 6
  levels: 4

encoder:
  type: gat # gat | interaction
  layers: 2
  heads: 4
  dropout: 0.0

processor:
  type: sliding_window  # sliding_window | interaction | hierarchical_interaction | hierarchical_sliding_window
  depth: 4
  num_heads: 4
  window: 4
  dropout: 0.1
  spatial_mixing_steps: 1

decoder:
  type: gat
  layers: 2
  heads: 4
  dropout: 0.0

embeddings:
  scan_angle_dim: 8
  pressure_level_dim: 8
  target_time_dim: 8
  num_pressure_levels: 16
  scan_angle_conditioning: project
  pressure_level_conditioning: project
